### ISSUE TITLE
API coverage tracking

### ISSUE THREAD

**Issue by mcornick** [mcornick/clilol#6]
These are all the API calls that should be supported before we can call this version 1.0.0:

## Account
- [x] Retrieve account information
- [x] Retrieve addresses for an account
- [x] Retrieve the account name
- [x] Set the account name
- [x] Retrieve active sessions
- [x] Remove a session
- [x] Retrieve account settings
- [x] Set account settings
## Address
- [x] Retrieve address availability
- [x] Retrieve address expiration
- [x] Retrieve public information about an address
- [x] Retrieve private information about an address
## DNS
- [x] Retrieve DNS records for an address
- [x] Create a new DNS record
- [x] Edit an existing DNS record
- [x] Delete a DNS record
## Directory
- [x] Retreive the address directory
## Email
- [x] Retrieve forwarding address(es)
- [x] Set forwarding address(es)
## Now Page
- [x] Retrieve /now Page
- [x] Retrieve the now.garden listing
- [x] Update /now Page
## PURLs
- [x] Create a new PURL
- [x] Retrieve a specific PURL
- [x] Retrieve a list of PURLs for an address
- [x] Delete a PURL
## Pastebin
- [x] Retrieve a specific paste
- [x] Retrieve an entire Pastebin
- [x] Retrieve listed pastes in a Pastebin
- [x] Create or update a paste in a Pastebin
- [x] Delete a paste from a Pastebin
## Preferences
- [x] Save an individual preference
## Service
- [x] Retrieve service information and statistics
## Statuslog
- [x] Retrieve an individual status for an address
- [x] Retrieve all statuses for an address
- [x] Share a new status
- [x] Update an existing status
- [x] Retrieve a Statuslog bio
- [x] Update a Statuslog bio
- [x] Retrieve the entire statuslog
- [x] Retrieve everyone’s latest status
## Theme
- [x] Retrieve a list of profile themes
- [x] Retrieve information about a theme
- [x] Retrieve a theme preview
## Web
- [x] Retrieve web page content
- [x] Update web page content and publish
- [x] Update web page content without publishing
- [x] Upload a profile picture
## Weblog
- [x] Retrieve weblog entries
- [x] Create a new weblog entry
- [x] Retrieve a weblog entry
- [x] Retrieve the latest weblog post
- [x] Delete a weblog entry
- [x] Retrieve weblog configuration
- [x] Update weblog configuration
- [x] Retrieve weblog template
- [x] Update weblog template
